### ISSUE TITLE
secret-bridge polling repos that are not listed in the config.toml

### ISSUE THREAD

**Issue by NiyiOdumosu** [duo-labs/secret-bridge#11]
So I noticed something interesting last week. I set up the `config.toml` to poll for a specific repo but when I ran the script, it began showing github events outputs for repos in our github organization that are not listed in the `config.toml`

Below are the monitors I am using:

`[monitors]`
    `organizations = ['Hearst-Hatchery']`
    `users = ['NiyiOdumosu']`
    `repos = ['Hearst-Hatchery/niyi-test']`

Per my understanding, I should only see polling events relating to the `Hearst-Hatchery/niyi-test` repo but I'm seeing detect-secret results of other repos that I am committing to. 

Below are the detect-secret outputs I am getting in my slack channel when I run the poll script

<img width="1201" alt="Screen Shot 2020-02-10 at 7 39 18 AM" src="https://user-images.githubusercontent.com/35928853/74150765-9d29c180-4bd8-11ea-807d-619c17acafbf.png">

As you can see it refers to 2 other repos (`anvil` and `essex`) that are in the `Hearst-Hatchery` organization even though I only put `Hearst-Hatchery/niyi-test` as the monitored repo. Is this monitoring every single github event I make with my github token despite me only specifying one repo in the monitors section? If so is there a way to only limit this to monitoring the repos put in the monitors section?

**Comment by jordan-wright** [comment]
Hey there!

I’ll take a closer look at this later, but I believe this is happening since you have something in the organizations field. You can think of the organizations, users, and repos fields as separate. So if you only want to monitor those specific repos, you only need to fill out the repos field.

By filling out all three, you’re saying:

* Monitor the Hearst-Hatchery organization
* Also monitor the NiyiOdumosu user
* Also monitor the niyi-test repo

Try only filling out the repos field and see if that helps.

**Comment by NiyiOdumosu** [comment]
Sorry I never responded but your suggestions worked. I limited the monitor to only the repo and it worked as expected. Thanks

**Comment by jordan-wright** [comment]
Good deal! Thanks for the heads up!
